// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: featureFlagConfig/feature_flag_config.proto

package feature_flag_config

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       *structpb.Struct       `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_featureFlagConfig_feature_flag_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_featureFlagConfig_feature_flag_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_featureFlagConfig_feature_flag_config_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetDetails() *structpb.Struct {
	if x != nil {
		return x.Details
	}
	return nil
}

type SetFeatureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsActive      bool                   `protobuf:"varint,2,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	BucketsOpened int32                  `protobuf:"varint,3,opt,name=buckets_opened,json=bucketsOpened,proto3" json:"buckets_opened,omitempty"`
	WhiteList     []string               `protobuf:"bytes,4,rep,name=white_list,json=whiteList,proto3" json:"white_list,omitempty"`
	BlackList     []string               `protobuf:"bytes,5,rep,name=black_list,json=blackList,proto3" json:"black_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFeatureRequest) Reset() {
	*x = SetFeatureRequest{}
	mi := &file_featureFlagConfig_feature_flag_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFeatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFeatureRequest) ProtoMessage() {}

func (x *SetFeatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_featureFlagConfig_feature_flag_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFeatureRequest.ProtoReflect.Descriptor instead.
func (*SetFeatureRequest) Descriptor() ([]byte, []int) {
	return file_featureFlagConfig_feature_flag_config_proto_rawDescGZIP(), []int{1}
}

func (x *SetFeatureRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetFeatureRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *SetFeatureRequest) GetBucketsOpened() int32 {
	if x != nil {
		return x.BucketsOpened
	}
	return 0
}

func (x *SetFeatureRequest) GetWhiteList() []string {
	if x != nil {
		return x.WhiteList
	}
	return nil
}

func (x *SetFeatureRequest) GetBlackList() []string {
	if x != nil {
		return x.BlackList
	}
	return nil
}

type SetFeatureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFeatureResponse) Reset() {
	*x = SetFeatureResponse{}
	mi := &file_featureFlagConfig_feature_flag_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFeatureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFeatureResponse) ProtoMessage() {}

func (x *SetFeatureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_featureFlagConfig_feature_flag_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFeatureResponse.ProtoReflect.Descriptor instead.
func (*SetFeatureResponse) Descriptor() ([]byte, []int) {
	return file_featureFlagConfig_feature_flag_config_proto_rawDescGZIP(), []int{2}
}

type GetFeaturesByOptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeatureNames  []string               `protobuf:"bytes,1,rep,name=feature_names,json=featureNames,proto3" json:"feature_names,omitempty"`
	IsActive      *bool                  `protobuf:"varint,2,opt,name=is_active,json=isActive,proto3,oneof" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeaturesByOptionsRequest) Reset() {
	*x = GetFeaturesByOptionsRequest{}
	mi := &file_featureFlagConfig_feature_flag_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeaturesByOptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeaturesByOptionsRequest) ProtoMessage() {}

func (x *GetFeaturesByOptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_featureFlagConfig_feature_flag_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeaturesByOptionsRequest.ProtoReflect.Descriptor instead.
func (*GetFeaturesByOptionsRequest) Descriptor() ([]byte, []int) {
	return file_featureFlagConfig_feature_flag_config_proto_rawDescGZIP(), []int{3}
}

func (x *GetFeaturesByOptionsRequest) GetFeatureNames() []string {
	if x != nil {
		return x.FeatureNames
	}
	return nil
}

func (x *GetFeaturesByOptionsRequest) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

type GetFeaturesByOptionsResponse struct {
	state         protoimpl.MessageState                                           `protogen:"open.v1"`
	Data          []*GetFeaturesByOptionsResponse_GetFeaturesByOptionsResponseData `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Error         *Error                                                           `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeaturesByOptionsResponse) Reset() {
	*x = GetFeaturesByOptionsResponse{}
	mi := &file_featureFlagConfig_feature_flag_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeaturesByOptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeaturesByOptionsResponse) ProtoMessage() {}

func (x *GetFeaturesByOptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_featureFlagConfig_feature_flag_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeaturesByOptionsResponse.ProtoReflect.Descriptor instead.
func (*GetFeaturesByOptionsResponse) Descriptor() ([]byte, []int) {
	return file_featureFlagConfig_feature_flag_config_proto_rawDescGZIP(), []int{4}
}

func (x *GetFeaturesByOptionsResponse) GetData() []*GetFeaturesByOptionsResponse_GetFeaturesByOptionsResponseData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetFeaturesByOptionsResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type FeatureAvailabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeatureName   string                 `protobuf:"bytes,1,opt,name=feature_name,json=featureName,proto3" json:"feature_name,omitempty"`
	ItemId        *string                `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3,oneof" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureAvailabilityRequest) Reset() {
	*x = FeatureAvailabilityRequest{}
	mi := &file_featureFlagConfig_feature_flag_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureAvailabilityRequest) ProtoMessage() {}

func (x *FeatureAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_featureFlagConfig_feature_flag_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*FeatureAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_featureFlagConfig_feature_flag_config_proto_rawDescGZIP(), []int{5}
}

func (x *FeatureAvailabilityRequest) GetFeatureName() string {
	if x != nil {
		return x.FeatureName
	}
	return ""
}

func (x *FeatureAvailabilityRequest) GetItemId() string {
	if x != nil && x.ItemId != nil {
		return *x.ItemId
	}
	return ""
}

type FeatureAvailabilityResponse struct {
	state         protoimpl.MessageState                                       `protogen:"open.v1"`
	Data          *FeatureAvailabilityResponse_FeatureAvailabilityResponseData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error         *Error                                                       `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureAvailabilityResponse) Reset() {
	*x = FeatureAvailabilityResponse{}
	mi := &file_featureFlagConfig_feature_flag_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureAvailabilityResponse) ProtoMessage() {}

func (x *FeatureAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_featureFlagConfig_feature_flag_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*FeatureAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_featureFlagConfig_feature_flag_config_proto_rawDescGZIP(), []int{6}
}

func (x *FeatureAvailabilityResponse) GetData() *FeatureAvailabilityResponse_FeatureAvailabilityResponseData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FeatureAvailabilityResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetFeaturesByOptionsResponse_GetFeaturesByOptionsResponseData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsActive      bool                   `protobuf:"varint,2,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	BucketsOpened int32                  `protobuf:"varint,3,opt,name=buckets_opened,json=bucketsOpened,proto3" json:"buckets_opened,omitempty"`
	WhiteList     []string               `protobuf:"bytes,4,rep,name=white_list,json=whiteList,proto3" json:"white_list,omitempty"`
	BlackList     []string               `protobuf:"bytes,5,rep,name=black_list,json=blackList,proto3" json:"black_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeaturesByOptionsResponse_GetFeaturesByOptionsResponseData) Reset() {
	*x = GetFeaturesByOptionsResponse_GetFeaturesByOptionsResponseData{}
	mi := &file_featureFlagConfig_feature_flag_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeaturesByOptionsResponse_GetFeaturesByOptionsResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeaturesByOptionsResponse_GetFeaturesByOptionsResponseData) ProtoMessage() {}

func (x *GetFeaturesByOptionsResponse_GetFeaturesByOptionsResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_featureFlagConfig_feature_flag_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeaturesByOptionsResponse_GetFeaturesByOptionsResponseData.ProtoReflect.Descriptor instead.
func (*GetFeaturesByOptionsResponse_GetFeaturesByOptionsResponseData) Descriptor() ([]byte, []int) {
	return file_featureFlagConfig_feature_flag_config_proto_rawDescGZIP(), []int{4, 0}
}

func (x *GetFeaturesByOptionsResponse_GetFeaturesByOptionsResponseData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetFeaturesByOptionsResponse_GetFeaturesByOptionsResponseData) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *GetFeaturesByOptionsResponse_GetFeaturesByOptionsResponseData) GetBucketsOpened() int32 {
	if x != nil {
		return x.BucketsOpened
	}
	return 0
}

func (x *GetFeaturesByOptionsResponse_GetFeaturesByOptionsResponseData) GetWhiteList() []string {
	if x != nil {
		return x.WhiteList
	}
	return nil
}

func (x *GetFeaturesByOptionsResponse_GetFeaturesByOptionsResponseData) GetBlackList() []string {
	if x != nil {
		return x.BlackList
	}
	return nil
}

type FeatureAvailabilityResponse_FeatureAvailabilityResponseData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureAvailabilityResponse_FeatureAvailabilityResponseData) Reset() {
	*x = FeatureAvailabilityResponse_FeatureAvailabilityResponseData{}
	mi := &file_featureFlagConfig_feature_flag_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureAvailabilityResponse_FeatureAvailabilityResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureAvailabilityResponse_FeatureAvailabilityResponseData) ProtoMessage() {}

func (x *FeatureAvailabilityResponse_FeatureAvailabilityResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_featureFlagConfig_feature_flag_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureAvailabilityResponse_FeatureAvailabilityResponseData.ProtoReflect.Descriptor instead.
func (*FeatureAvailabilityResponse_FeatureAvailabilityResponseData) Descriptor() ([]byte, []int) {
	return file_featureFlagConfig_feature_flag_config_proto_rawDescGZIP(), []int{6, 0}
}

func (x *FeatureAvailabilityResponse_FeatureAvailabilityResponseData) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *FeatureAvailabilityResponse_FeatureAvailabilityResponseData) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_featureFlagConfig_feature_flag_config_proto protoreflect.FileDescriptor

const file_featureFlagConfig_feature_flag_config_proto_rawDesc = "" +
	"\n" +
	"+featureFlagConfig/feature_flag_config.proto\x12\x17api.feature_flag_config\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\"h\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x121\n" +
	"\adetails\x18\x03 \x01(\v2\x17.google.protobuf.StructR\adetails\"\xa9\x01\n" +
	"\x11SetFeatureRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tis_active\x18\x02 \x01(\bR\bisActive\x12%\n" +
	"\x0ebuckets_opened\x18\x03 \x01(\x05R\rbucketsOpened\x12\x1d\n" +
	"\n" +
	"white_list\x18\x04 \x03(\tR\twhiteList\x12\x1d\n" +
	"\n" +
	"black_list\x18\x05 \x03(\tR\tblackList\"\x14\n" +
	"\x12SetFeatureResponse\"r\n" +
	"\x1bGetFeaturesByOptionsRequest\x12#\n" +
	"\rfeature_names\x18\x01 \x03(\tR\ffeatureNames\x12 \n" +
	"\tis_active\x18\x02 \x01(\bH\x00R\bisActive\x88\x01\x01B\f\n" +
	"\n" +
	"_is_active\"\xfb\x02\n" +
	"\x1cGetFeaturesByOptionsResponse\x12j\n" +
	"\x04data\x18\x01 \x03(\v2V.api.feature_flag_config.GetFeaturesByOptionsResponse.GetFeaturesByOptionsResponseDataR\x04data\x124\n" +
	"\x05error\x18\x02 \x01(\v2\x1e.api.feature_flag_config.ErrorR\x05error\x1a\xb8\x01\n" +
	" GetFeaturesByOptionsResponseData\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tis_active\x18\x02 \x01(\bR\bisActive\x12%\n" +
	"\x0ebuckets_opened\x18\x03 \x01(\x05R\rbucketsOpened\x12\x1d\n" +
	"\n" +
	"white_list\x18\x04 \x03(\tR\twhiteList\x12\x1d\n" +
	"\n" +
	"black_list\x18\x05 \x03(\tR\tblackList\"i\n" +
	"\x1aFeatureAvailabilityRequest\x12!\n" +
	"\ffeature_name\x18\x01 \x01(\tR\vfeatureName\x12\x1c\n" +
	"\aitem_id\x18\x02 \x01(\tH\x00R\x06itemId\x88\x01\x01B\n" +
	"\n" +
	"\b_item_id\"\x92\x02\n" +
	"\x1bFeatureAvailabilityResponse\x12h\n" +
	"\x04data\x18\x01 \x01(\v2T.api.feature_flag_config.FeatureAvailabilityResponse.FeatureAvailabilityResponseDataR\x04data\x124\n" +
	"\x05error\x18\x02 \x01(\v2\x1e.api.feature_flag_config.ErrorR\x05error\x1aS\n" +
	"\x1fFeatureAvailabilityResponseData\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason2\xef\x03\n" +
	"\x18FeatureFlagConfigService\x12\x81\x01\n" +
	"\n" +
	"SetFeature\x12*.api.feature_flag_config.SetFeatureRequest\x1a+.api.feature_flag_config.SetFeatureResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/feature/set\x12\xa8\x01\n" +
	"\x14GetFeaturesByOptions\x124.api.feature_flag_config.GetFeaturesByOptionsRequest\x1a5.api.feature_flag_config.GetFeaturesByOptionsResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/feature/getByOptions\x12\xa3\x01\n" +
	"\x18CheckFeatureAvailability\x123.api.feature_flag_config.FeatureAvailabilityRequest\x1a4.api.feature_flag_config.FeatureAvailabilityResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/feature/checkB\x17Z\x15./feature_flag_configb\x06proto3"

var (
	file_featureFlagConfig_feature_flag_config_proto_rawDescOnce sync.Once
	file_featureFlagConfig_feature_flag_config_proto_rawDescData []byte
)

func file_featureFlagConfig_feature_flag_config_proto_rawDescGZIP() []byte {
	file_featureFlagConfig_feature_flag_config_proto_rawDescOnce.Do(func() {
		file_featureFlagConfig_feature_flag_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_featureFlagConfig_feature_flag_config_proto_rawDesc), len(file_featureFlagConfig_feature_flag_config_proto_rawDesc)))
	})
	return file_featureFlagConfig_feature_flag_config_proto_rawDescData
}

var file_featureFlagConfig_feature_flag_config_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_featureFlagConfig_feature_flag_config_proto_goTypes = []any{
	(*Error)(nil),                                                         // 0: api.feature_flag_config.Error
	(*SetFeatureRequest)(nil),                                             // 1: api.feature_flag_config.SetFeatureRequest
	(*SetFeatureResponse)(nil),                                            // 2: api.feature_flag_config.SetFeatureResponse
	(*GetFeaturesByOptionsRequest)(nil),                                   // 3: api.feature_flag_config.GetFeaturesByOptionsRequest
	(*GetFeaturesByOptionsResponse)(nil),                                  // 4: api.feature_flag_config.GetFeaturesByOptionsResponse
	(*FeatureAvailabilityRequest)(nil),                                    // 5: api.feature_flag_config.FeatureAvailabilityRequest
	(*FeatureAvailabilityResponse)(nil),                                   // 6: api.feature_flag_config.FeatureAvailabilityResponse
	(*GetFeaturesByOptionsResponse_GetFeaturesByOptionsResponseData)(nil), // 7: api.feature_flag_config.GetFeaturesByOptionsResponse.GetFeaturesByOptionsResponseData
	(*FeatureAvailabilityResponse_FeatureAvailabilityResponseData)(nil),   // 8: api.feature_flag_config.FeatureAvailabilityResponse.FeatureAvailabilityResponseData
	(*structpb.Struct)(nil),                                               // 9: google.protobuf.Struct
}
var file_featureFlagConfig_feature_flag_config_proto_depIdxs = []int32{
	9, // 0: api.feature_flag_config.Error.details:type_name -> google.protobuf.Struct
	7, // 1: api.feature_flag_config.GetFeaturesByOptionsResponse.data:type_name -> api.feature_flag_config.GetFeaturesByOptionsResponse.GetFeaturesByOptionsResponseData
	0, // 2: api.feature_flag_config.GetFeaturesByOptionsResponse.error:type_name -> api.feature_flag_config.Error
	8, // 3: api.feature_flag_config.FeatureAvailabilityResponse.data:type_name -> api.feature_flag_config.FeatureAvailabilityResponse.FeatureAvailabilityResponseData
	0, // 4: api.feature_flag_config.FeatureAvailabilityResponse.error:type_name -> api.feature_flag_config.Error
	1, // 5: api.feature_flag_config.FeatureFlagConfigService.SetFeature:input_type -> api.feature_flag_config.SetFeatureRequest
	3, // 6: api.feature_flag_config.FeatureFlagConfigService.GetFeaturesByOptions:input_type -> api.feature_flag_config.GetFeaturesByOptionsRequest
	5, // 7: api.feature_flag_config.FeatureFlagConfigService.CheckFeatureAvailability:input_type -> api.feature_flag_config.FeatureAvailabilityRequest
	2, // 8: api.feature_flag_config.FeatureFlagConfigService.SetFeature:output_type -> api.feature_flag_config.SetFeatureResponse
	4, // 9: api.feature_flag_config.FeatureFlagConfigService.GetFeaturesByOptions:output_type -> api.feature_flag_config.GetFeaturesByOptionsResponse
	6, // 10: api.feature_flag_config.FeatureFlagConfigService.CheckFeatureAvailability:output_type -> api.feature_flag_config.FeatureAvailabilityResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_featureFlagConfig_feature_flag_config_proto_init() }
func file_featureFlagConfig_feature_flag_config_proto_init() {
	if File_featureFlagConfig_feature_flag_config_proto != nil {
		return
	}
	file_featureFlagConfig_feature_flag_config_proto_msgTypes[3].OneofWrappers = []any{}
	file_featureFlagConfig_feature_flag_config_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_featureFlagConfig_feature_flag_config_proto_rawDesc), len(file_featureFlagConfig_feature_flag_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_featureFlagConfig_feature_flag_config_proto_goTypes,
		DependencyIndexes: file_featureFlagConfig_feature_flag_config_proto_depIdxs,
		MessageInfos:      file_featureFlagConfig_feature_flag_config_proto_msgTypes,
	}.Build()
	File_featureFlagConfig_feature_flag_config_proto = out.File
	file_featureFlagConfig_feature_flag_config_proto_goTypes = nil
	file_featureFlagConfig_feature_flag_config_proto_depIdxs = nil
}
